config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :reservations
  root 'welcome#index'

  resources :periods
  resources :rooms

end

app/models/period.rb
class Period < ActiveRecord::Base
	validates :fecha_inicio, uniqueness: true, presence: true
	validates :fecha_finalizacion, uniqueness: true, presence: true

	has_many :reservations
end

app/controllers/periods_controller.rb
class PeriodsController < ApplicationController
  before_action :set_period, only: [:show, :edit, :update, :destroy]

  # GET /periods
  # GET /periods.json
  def index
    @periods = Period.all
  end

  # GET /periods/1
  # GET /periods/1.json
  def show
  end

  # GET /periods/new
  def new
    @period = Period.new
  end

  # GET /periods/1/edit
  def edit
  end

  # POST /periods
  # POST /periods.json
  def create
    @period = Period.new(period_params_new)

    respond_to do |format|
      if @period.save
        format.html { redirect_to @period, notice: 'Period was successfully created.' }
        format.json { render :show, status: :created, location: @period }
      else
        format.html { render :new }
        format.json { render json: @period.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /periods/1
  # PATCH/PUT /periods/1.json
  def update
    respond_to do |format|
      if @period.update(period_params_update)
        format.html { redirect_to @period, notice: 'Period was successfully updated.' }
        format.json { render :show, status: :ok, location: @period }
      else
        format.html { render :edit }
        format.json { render json: @period.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /periods/1
  # DELETE /periods/1.json
  def destroy
    @period.destroy
    respond_to do |format|
      format.html { redirect_to periods_url, notice: 'Period was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_period
      @period = Period.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def period_params_new
      params.require(:period).permit(:fecha_inicio, :fecha_finalizacion)
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def period_params_update
      params.require(:period).permit(:fecha_finalizacion)
    end
end

app/helpers/periods_helper.rb
module PeriodsHelper
end

app/views/periods/_form.html.erb
<div class="row">
    <div class="col s12 m6">
        <%= form_for(@period) do |f| %>

            <% if @period.errors.any? %>
                <div id="error_explanation" class="card red lighten-5">
                    <div class="card-content">
                        <span class="card-title"><%= pluralize(@period.errors.count, "error") %></span><br>
                        <span class="card-title">prohibited this period from being saved:</span>
                        <ul>
                            <% @period.errors.full_messages.each do |message| %>
                            <li><%= message %></li>
                            <% end %>
                        </ul>
                    </div>
                </div>
            <% end %>
        <br>
        <div class="input-field">
            <%= f.label :fecha_inicio %>
            <%= f.text_field :fecha_inicio, :class => "datepicker" %>
        </div>
        <div class="input-field">
            <%= f.label :fecha_finalizacion %>
            <%= f.text_field :fecha_finalizacion, :class => "datepicker" %>
        </div>

        <div class="input-field">
            <%= f.submit :class => "btn red white-text" %>
        </div>

        <% end %>
    </div>
</div>

app/views/periods/edit.html.erb
<div class="container">
	<h1>Editing Period</h1>

	<%= form_for(@period) do |f| %>
		<% if @period.errors.any? %>
			<div id="error_explanation" class="card red lighten-5">
				<div class="card-content">
					<spam class="card-title"><%= pluralize(@period.errors.count, "error") %></spam><br>
					<span class="card-title">prohibited this period from being saved:</span>
					<ul>
						<% @period.errors.full_messages.each do |message| %>
						<li><%= message %></li>
						<% end %>
					</ul>
				</div>
			</div>
		<% end %>

	<div class="input-field">
	<%= f.label :fecha_finalizacion %>
		<%= f.text_field :fecha_finalizacion, :class => "datepicker" %>
	</div>
	<div class="input-field">
		<%= f.submit :class => "btn red white-text" %>
	</div>
	<% end %>

	<%= link_to 'Ver', @period, :class => "btn white red-text" %> |
	<%= link_to 'Atras', periods_path, :class => "btn white red-text" %>
</div>

app/views/periods/index.html.erb
<div class="container">
    <p id="notice"><%= notice %></p>

    <h1>Periodos</h1>

    <!-- -->
    <div class="row">
        <div class="col s6 m2 red">
            <p class="white-text">INICIO</p>
        </div>
        <div class="col s6 m2 red">
            <p class="white-text">FINALIZACION</p>
        </div>
        <div class="col m2 red hide-on-small-only center">
            <p class="white-text">ACTIONS</p>
        </div>
    </div>
    <% @periods.each do |period| %>
        <div class="row">
            <div class="col s6 m2">
                <p class="red-text"><%= period.fecha_inicio %></p>
            </div>
            <div class="col s6 m2">
                <p class="red-text"><%= period.fecha_finalizacion %></p>
            </div>
            <div class="col s12 m2">
                <%= link_to '<i class="material-icons">close</i>'.html_safe , period, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn-floating red right" %>
                <%= link_to '<i class="material-icons">edit</i>'.html_safe, edit_period_path(period), :class => "btn-floating red right" %>
            </div>
        </div>
    <% end %>
    <!-- -->
    <br>

    <%= link_to '<i class="material-icons red-text">add</i>'.html_safe, new_period_path, :class  => "btn-floating btn-large white" %>
</div>

app/views/periods/new.html.erb
<div class="container">
	<h1>Nuevo Periodo</h1>

	<div class="chip red white-text">
		<i class="material-icons">close</i>
		Hoy: <%= Date.today %>
	</div>

	<%= render 'form' %>

	<%= link_to 'Atras', periods_path, :class => "btn white red-text" %>
</div>

app/views/periods/show.html.erb
<div class="container">
	<p id="notice"><%= notice %></p>

	<div class="row">
	  	<div class="col s12 m6 red white-text">
	  		INICIO:
	  	</div><br>
	  	<div class="col m2 red white-text center-align hide-on-med-and-down">
	  		Dia
	  	</div>
	  	<div class="col m2 red white-text center-align hide-on-med-and-down">
	  		Mes
	  	</div>
	  	<div class="col m2 red white-text center-align hide-on-med-and-down">
	  		A&ntilde;o
	  	</div><br class="hide-on-med-and-down">
  		<div class="col s4 m2 red-text center-align">
	  		<%= @period.fecha_inicio.day %>
	  	</div>
	  	<div class="col s4 m2 red-text center-align">
	  		<%= @period.fecha_inicio.month %>
	  	</div>
	  	<div class="col s4 m2 red-text center-align">
	  		<%= @period.fecha_inicio.year %>
	  	</div>
	</div>

	<div class="row">
	  	<div class="col s12 m6 red white-text">
	  		FINALIZACION:
	  	</div><br>
	  	<div class="col m2 red white-text center-align hide-on-med-and-down">
	  		Dia
	  	</div>
	  	<div class="col m2 red white-text center-align hide-on-med-and-down">
	  		Mes
	  	</div>
	  	<div class="col m2 red white-text center-align hide-on-med-and-down">
	  		A&ntilde;o
	  	</div><br class="hide-on-med-and-down">
  		<div class="col s4 m2 red-text center-align">
	  		<%= @period.fecha_finalizacion.day %>
	  	</div>
	  	<div class="col s4 m2 red-text center-align">
	  		<%= @period.fecha_finalizacion.month %>
	  	</div>
	  	<div class="col s4 m2 red-text center-align">
	  		<%= @period.fecha_finalizacion.year %>
	  	</div>
	</div>
	<%= link_to 'Editar', edit_period_path(@period), :class => "btn white red-text" %> |
	<%= link_to 'Atras', periods_path, :class => "btn white red-text" %>
</div>