config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :reservations
  root 'welcome#index'

  resources :periods
  resources :rooms

end

app/models/room.rb
class Room < ActiveRecord::Base
	validate :cantd_mayorque_cantt

	validates :nombre, uniqueness: true

	has_many :reservations

	def cantd_mayorque_cantt
		if cantidad_disponible > cantidad_total
			errors.add(:cantidad_disponible, "Cantidad incorrecta")
		end
	end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params_new)
    @room.cantidad_disponible = @room.cantidad_total

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params_update)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params_new
      params.require(:room).permit(:nombre, :cantidad_total)
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params_update
      params.require(:room).permit(:cantidad_disponible)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_for(@room) do |f| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% @room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :cantidad_total %><br>
    <%= f.number_field :cantidad_total %>
  </div>
  <div class="field">
    <%= f.label :cantidad_disponible %><br>
    <%= f.number_field :cantidad_disponible %>
  </div>
  <div class="actions">
    <%= f.submit :class => "btn red white-text" %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col s12 m6">
			<h1>Editar Sala</h1>

			<%= form_for(@room) do |f| %>
				<% if @room.errors.any? %>
					<div id="error_explanation" class="card red lighten-5">
						<div class="card-content">
							<spam class="card-title"><%= pluralize(@room.errors.count, "error") %></spam><br>
							<spam class="card-title">prohibited this room from being saved:</spam>
							<ul>
								<% @room.errors.full_messages.each do |message| %>
								<li><%= message %></li>
								<% end %>
							</ul>
						</div>
					</div>
				<% end %>
		</div>
	</div>
	<div class="row">
		<div class="col s12 m6">
				<div class="input-field">
					<%= f.label :cantidad_total %>
					<%= f.number_field :cantidad_total, :readonly => true%>
				</div>
		</div>
		<div class="col s12 m3">
				<div class="input-field">
				    <%= f.label :cantidad_disponible %>
				    <%= f.number_field :cantidad_disponible %>
				</div>
		</div>
		<div class="col s12 m6">
				<div class="actions">
					<%= f.submit :class => "btn red white-text" %>
				</div>
			<% end %>
		</div>
	</div>

	<%= link_to 'Ver', @room, :class => "btn white red-text" %> |
	<%= link_to 'Atras', rooms_path, :class => "btn white red-text" %>
</div>

app/views/rooms/index.html.erb
<div class="container">
    <p id="notice"><%= notice %></p>

    <h1>Salas</h1>

    <div class="row">
        <div class="col s4 m2 red center">
            <p class="white-text">NOMBRE</p>
        </div>
        <div class="col s4 m2 red center">
            <p class="white-text">EQUIPOS</p>
        </div>
        <div class="col s4 m2 red center">
            <p class="white-text">DISPONIBLES</p>
        </div>
        <div class="col m6 hide-on-small-only red center">
            <p class="white-text">ACCIONES</p>
        </div>
    </div>
    <!-- -->
    <% @rooms.each do |room| %>
        <div class="row">
            <div class="col s4 m2 center">
                <p class="red-text"><%= room.nombre %></p>
            </div>
            <div class="col s4 m2 center">
                <p class="red-text"><%= room.cantidad_total %></p>
            </div>
            <div class="col s4 m2 center">
                <p class="red-text"><%= room.cantidad_disponible %></p>
            </div>
            <div class="col s12 m6 right">
                <%= link_to '<i class="material-icons">close</i>'.html_safe, room, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn-floating red white-text right" %>
                <%= link_to '<i class="material-icons">edit</i>'.html_safe, edit_room_path(room), :class => "btn-floating red white-text right" %>
            </div>
        </div>
    <% end %>

    <br>

    <%= link_to '<i class="material-icons red-text">add</i>'.html_safe, new_room_path, :class => "btn-floating btn-large white" %>
</div>

app/views/rooms/new.html.erb
<div class="container">
	<div class="row">
		<div class="col s12 m6">
			<h1>Nueva Sala</h1>

			<%= form_for(@room) do |f| %>
				<% if @room.errors.any? %>
					<div id="error_explanation" class="card red lighten-5">
						<div class="card-content">
							<spam class="card-title"><%= pluralize(@room.errors.count, "error") %></spam><br>
							<spam class="card-title">prohibited this room from being saved:</spam>
							<ul>
								<% @room.errors.full_messages.each do |message| %>
								<li><%= message %></li>
								<% end %>
							</ul>
						</div>
					</div>
				<% end %>
		</div>
	</div>
	<div class="row">
		<div class="col s12 m6">
				<div class="input-field">
					<%= f.label :nombre %>
					<%= f.text_field :nombre %>
				</div>
		</div>
		<div class="col s12 m3">
				<div class="input-field">
					<%= f.label :cantidad_total %>
					<%= f.number_field :cantidad_total %>
				</div>
		</div>
		<div class="col s12 m6">
				<div class="actions">
					<%= f.submit :class => "btn red white-text" %>
				</div>
			<% end %>
		</div>
	</div>
	<%= link_to 'Atras', rooms_path, :class => "btn white red-text" %>
</div>

app/views/rooms/show.html.erb
<div class="container">
	<p id="notice"><%= notice %></p>

	<div class="row">
		<p>
			<strong>Nombre:</strong>
			<%= @room.nombre %>
		</p>

		<p>
			<strong>Cantidad total:</strong>
			<%= @room.cantidad_total %>
		</p>

		<p>
			<strong>Cantidad disponible:</strong>
			<%= @room.cantidad_disponible %>
		</p>
	</div>

	<%= link_to 'Edit', edit_room_path(@room), :class => "btn white red-text" %> |
	<%= link_to 'Back', rooms_path, :class => "btn white red-text" %>
</div>