config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :reservations
  root 'welcome#index'

  resources :periods
  resources :rooms

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SalaSistemas</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
	<nav class="red">
		<div class="container">
			<a href="#" class="button-collapse" data-activates="mobile"><i class="material-icons">menu</i></a>
			<a href="#" class="brand-logo truncate hide-on-large-only">Sala de Sistemas</a>
			<ul class="hide-on-med-and-down">
				<li><%= link_to root_path do %><i class="material-icons left">home</i>INICIO<% end %></li>
				<li><%= link_to periods_path do %><i class="material-icons left">date_range</i>PERIODOS<% end %></li>
				<li><%= link_to reservations_path do %><i class="material-icons left">event</i>RESERVACIONES<% end %></li>
				<li><%= link_to rooms_path do %><i class="material-icons left">room</i>SALAS<% end %></li>
				<li><%= link_to users_path do %><i class="material-icons left">account_circle</i>USUARIOS<% end %></li>
			</ul>
			<ul id="mobile" class="side-nav">
				<li><%= link_to root_path do %><i class="material-icons left">home</i>INICIO<% end %></li>
				<li><%= link_to periods_path do %><i class="material-icons left">date_range</i>PERIODS<% end %></li>
				<li><%= link_to reservations_path do %><i class="material-icons left">event</i>RESERVATIONS<% end %></li>
				<li><%= link_to rooms_path do %><i class="material-icons left">room</i>ROOMS<% end %></li>
				<li><%= link_to users_path do %><i class="material-icons left">account_circle</i>USERS<% end %></li>
			</ul>
		</div>
	</nav>
</header>

<main>
	<%= yield %>
</main>

<footer class="page-footer white">
	<div class="footer-copyright">
		<div class="container black-text">
			© 2016 Universidad del Valle - sede Carbonera
		</div>
	</div>
</footer>
</body>
</html>